// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Robot = require("./robot.bs.js");
var Utils = require("../utils.bs.js");

function create(width, height) {
  return {
          width: width,
          height: height
        };
}

function keepInsideRoom(room, robot) {
  var match = robot.coord;
  var x = Utils.clampInt(match.x, room.width, 1);
  var y = Utils.clampInt(match.y, room.height, 1);
  return Robot.create(robot.facing, {
              x: x,
              y: y
            });
}

exports.create = create;
exports.keepInsideRoom = keepInsideRoom;
/* No side effect */
