// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var App = require("./App.bs.js");
var React = require("react");
var ReactDom = require("react-dom");
var Caml_option = require("rescript/lib/js/caml_option.js");

var appElement = document.querySelector("#app");

if (appElement == null) {
  console.log("Could not find anchor element.");
} else {
  ReactDom.render(React.createElement(App.make, {}), appElement);
}

var appElement$1 = (appElement == null) ? undefined : Caml_option.some(appElement);

exports.appElement = appElement$1;
/* appElement Not a pure module */
