// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function clampInt(number, max, min) {
  return Math.max(min, Math.min(number, max));
}

exports.clampInt = clampInt;
/* No side effect */
